### ISSUE TITLE
copyright holder

### ISSUE THREAD

**Issue by EmilHvitfeldt** [EmilHvitfeldt/emoji#1]
Hello @hadley & @romainfrancois, I am finishing wrapping up the {emoji} package. This package naturally borrows a lot from https://github.com/hadley/emo (with several updates to make it work with newer data). I just want to make sure you are okay with your attribution in this package.

https://github.com/EmilHvitfeldt/emoji/blob/88ad7a6728bbdd2e65f20699aae1e3d61f8bcd44/DESCRIPTION#L10-L18

**Comment by hadley** [comment]
I think "ctb" would be more appropriate here. I think "cph" implies holding copyright via employment etc.

**Comment by EmilHvitfeldt** [comment]
Thank you! 

updated:
https://github.com/EmilHvitfeldt/emoji/commit/a524938663c5f629328038caeb3127154922ef62#diff-9cc358405149db607ff830a16f0b4b21f7366e3c99ec00d52800acebe21b231cL10-L18
