### ISSUE TITLE
feature request: a ggplot element that uses emojis

### ISSUE THREAD

**Issue by tanho63** [EmilHvitfeldt/emoji#6]
It would be really cool if there was an element/geom_emoji that would take the emoji nickname and use it to plot/label/aesthetic within ggplot!

**Comment by EmilHvitfeldt** [comment]
with the advent of the {ragg} package, i don't think we really need this. Or at least i won't put it in this package

read more here: https://www.tidyverse.org/blog/2021/02/modern-text-features/

```r
library(tidyverse)
library(emoji)

mtcars |>
  mutate(car = if_else(hp > 100, emoji("racing_car"), emoji("car"))) |>
  ggplot(aes(mpg, disp, label = car)) +
  geom_text()
```

![Rplot](https://github.com/user-attachments/assets/52ff389d-c755-4da8-9509-2e87ea377669)
