### ISSUE TITLE
unable to get the modifier

### ISSUE THREAD

**Issue by ncz11** [EmilHvitfeldt/emoji#9]
in a plot(ggpredict) setup, I am trying to use  emojis with modifier (black man, white man) in the caption. for some reason, the emoji search for man only returns a yellow-faced man. is there an issue with the library or what is it that I am doing wrong?

**Comment by EmilHvitfeldt** [comment]
sorry for very late reply. this should be possible

``` r
library(emoji)

emoji("man frowning")
#> [1] "🙍‍♂️"
emoji("man frowning light skin tone")
#> [1] "🙍🏻‍♂️"
```

<sup>Created on 2024-10-27 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>
